enqueue:
    default:
        transport:
            dsn: "%env(ENQUEUE_DSN)%"
            rdkafka:
                global:
                    metadata.broker.list: "%env(KAFKA_BROKER_LIST)%"
                    group.id: "symfony-messenger"
                    enable.auto.commit: "false"
                topic:
                    auto.offset.reset: "earliest"
        client: null
